### ISSUE TITLE
Electron version and Node version can’t be reconciled

### ISSUE THREAD

**Issue by ticky** [gavinbenda/platinum-md#36]
The Electron version currently in use in master is old enough that it ships nodejs 8.x, meanwhile devDependency `cfonts` requires node 10.x or newer, and will thus fail installing dependencies as currently `yarn.lock`ed in master.

This is currently meaning that I cannot get a node version installed which satisfies the dependencies of cfonts while also producing binaries compatible with Electron’s node version, and thus `usb-detection` fails to run under node 10.x, bringing down the whole application:

```
Uncaught Error: The module 'platinum-md/node_modules/usb-detection/build/Release/detection.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (platinum-md/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (platinum-md/node_modules/usb-detection/index.js:13:37)
```

It seems that Electron needs updating if anyone else is going to be able to contribute meaningfully to the JS side of this project!

**Comment by gavinbenda** [comment]
Hey there - to fix this (for now), just run `./node_modules/.bin/electron-rebuild`

**Comment by gavinbenda** [comment]
Have automated this in the build process.
