### ISSUE TITLE
LAM-Z05

### ISSUE THREAD

**Issue by is-that-a-thing-now** [gavinbenda/platinum-md#84]
Hello,

I have been playing with the latest release candidate of Platinum MD. I am running it on OSX, and have tested an MDS-NT1, and LAM-Z05. Figured I'd let you know how it went.

For the NT1 it works perfectly, no issues.

Not so much for the LAM-Z05. It seems to kinda work, but had a few hiccups. For reference, the Z05 seems to work with D9's test app, but fails to connect with web minidisc. I have the full logs saved from writing a complete album, but have excerpts here to make it easier.

When first plugging in the device and trying to connect it cycles between connected and negotiating (the device is also incorrectly labeled as the Z10, but I don't think there is much difference). Image: https://i.imgur.com/Dl12boc.png (Sorry, can't seem to copy and paste from the console). Eventually it stops cycling and stays connected.

If I try to send a file, it seems to transfer correctly, but sometimes fails giving the following error. Image: https://i.imgur.com/amxzAcl.png Sending a whole album it failed two or three times at different tracks before it completed.

The completed disc did not playback the first two tracks. After trying it in another device it failed playback smoothly at all (skipping and freezing). I worried it was a dirty laser or something (the Z05 does give a disc error with known ok discs occasionally), but I rewrote the disc using SonicStage on the Z05 and it works perfectly, leading me to believe it is a software issue. I'll give it another run through just in case.

If there is anything you want me to test, let me know.

**Comment by gavinbenda** [comment]
Re-visiting this one, I don't have that model to test with - would be worth another test with the latest v1.2.0 release to see if it's still not working.

**Comment by gavinbenda** [comment]
Awesome - there is a full changelog in the release notes, but the fix for this would be in the updated linux-minidisc binaries that have also been updated to better support HiFi units.

**Comment by is-that-a-thing-now** [comment]
So, I checked it out myself.  It seems to work for the most part.  It can read and write discs, and even control playback.

The one issue I found is that it always shows the disc title as <untitled> even if the disc actually has one, and even though it lets you set one (and it appears to write said title, even though it continues to display it as <untitled> within the app).

**Comment by is-that-a-thing-now** [comment]
Hello,

I have been extensively testing PMD over the last few days, and talking with another user who owns a Z05 in the minidisc.wiki discord.

Other than the above mentioned title issue, I have spotted one issue.  When trying to write a large amount of tracks (in this case 70+ for an English listening disc, note that all tracks still clock in under 80 minutes), it often throws up errors around 30 or so and starts skipping tracks.  Bellow is the excerpt from the logs:

`New Track: 34

renderer.js:56 netmd_secure_commit_track : No error

renderer.js:56 netmd_secure_session_key_forget : No error

renderer.js:56 netmd_secure_leave_session : No error

renderer.js:56 netmd_release_dev : Unknown Error

renderer.js:56 netmdcli send returned Success code 0
renderer.js:56 no-connection
renderer.js:56 Object
renderer.js:56 Attempting to read from NetMD
renderer.js:56 progress Idle
renderer.js:56 transfer-completed
renderer.js:56 Object
renderer.js:56 Processing track: 35
renderer.js:56 Directory createdC:\Users\Ender\AppData\Local\Temppmd-temp
renderer.js:56 C:\Users\Ender\Desktop\New folder\CD1-36.mp3
renderer.js:56 Starting conversion in <SP> mode
renderer.js:56 progress Converting to Wav
renderer.js:56 Starting WAV conversion process using ffmpeg: C:\Users\Ender\Desktop\New folder\CD1-36.mp3 --> C:\Users\Ender\AppData\Local\Temppmd-temp\ƒgƒ‰ƒbƒN 36 - No Artist.wav
renderer.js:56 Spawned Ffmpeg with command:  ffmpeg -i C:\Users\Ender\Desktop\New folder\CD1-36.mp3 -y -ar 44100 -acodec pcm_s16le C:\Users\Ender\AppData\Local\Temppmd-temp\ƒgƒ‰ƒbƒN 36 - No Artist.wav
renderer.js:56 Processing: 00:00:34.14 done 5882 kilobytes
renderer.js:56 progress Converting Track
renderer.js:56 ffmpeg completed successfully
renderer.js:56 progress Idle
renderer.js:56 Title: 36
renderer.js:56 Conversion Complete: C:\Users\Ender\AppData\Local\Temppmd-temp\ƒgƒ‰ƒbƒN 36 - No Artist.wav
renderer.js:56 progress Sending to Player
renderer.js:56 Attempting to send to NetMD device
renderer.js:56 Error opening netmd
Error while opening the USB device

renderer.js:56 netmdcli error, returned 1
renderer.js:56 progress Idle
renderer.js:56 undefined
renderer.js:56 Attempt to send file failed, retrying...
renderer.js:56 Error opening netmd
Error while opening the USB device

renderer.js:56 netmdcli error, returned 1
renderer.js:56 progress Idle
renderer.js:56 undefined
renderer.js:56 Attempt to send file failed, retrying...
renderer.js:56 Error opening netmd
Error while opening the USB device

renderer.js:56 netmdcli error, returned 1
renderer.js:56 progress Idle
renderer.js:56 undefined
renderer.js:56 Attempt to send file failed, retrying...
renderer.js:56 Error opening netmd
Error while opening the USB device

renderer.js:56 netmdcli error, returned 1
renderer.js:56 progress Idle
renderer.js:56 undefined
renderer.js:56 Attempt to send file failed, retrying...
renderer.js:56 Error opening netmd
Error while opening the USB device

renderer.js:56 netmdcli error, returned 1
renderer.js:56 progress Idle
renderer.js:56 undefined
renderer.js:56 Attempt to send file failed, retrying...
renderer.js:56 {
  "device":"Sony LAM-10",
  "title":"<Untitled>",
  "recordedTime":"00:36:19.00",
  "totalTime":"01:20:59.11",
  "availableTime":"00:44:40.89",
  "tracks":[
    {
      "no":0,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:24:61",
      "name":"1"
    },
    {
      "no":1,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:48:29",
      "name":"2"
    },
    {
      "no":2,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:34:00",
      "name":"3"
    },
    {
      "no":3,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:50:50",
      "name":"4"
    },
    {
      "no":4,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:46:75",
      "name":"5"
    },
    {
      "no":5,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:47:11",
      "name":"6"
    },
    {
      "no":6,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:50:00",
      "name":"7"
    },
    {
      "no":7,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:29:24",
      "name":"8"
    },
    {
      "no":8,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:19:25",
      "name":"9"
    },
    {
      "no":9,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:34:03",
      "name":"10"
    },
    {
      "no":10,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:41:33",
      "name":"11"
    },
    {
      "no":11,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:51:63",
      "name":"12"
    },
    {
      "no":12,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:43:22",
      "name":"13"
    },
    {
      "no":13,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:12:14",
      "name":"14"
    },
    {
      "no":14,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:28:42",
      "name":"15"
    },
    {
      "no":15,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:20:67",
      "name":"16"
    },
    {
      "no":16,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:51:24",
      "name":"17"
    },
    {
      "no":17,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:37:17",
      "name":"18"
    },
    {
      "no":18,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:34:75",
      "name":"19"
    },
    {
      "no":19,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:43:42",
      "name":"20"
    },
    {
      "no":20,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:05:00",
      "name":"21"
    },
    {
      "no":21,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:12:85",
      "name":"22"
    },
    {
      "no":22,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:46:04",
      "name":"23"
    },
    {
      "no":23,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:45:65",
      "name":"24"
    },
    {
      "no":24,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:04:76",
      "name":"25"
    },
    {
      "no":25,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:41:38",
      "name":"26"
    },
    {
      "no":26,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:44:00",
      "name":"27"
    },
    {
      "no":27,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:14:21",
      "name":"28"
    },
    {
      "no":28,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:49:70",
      "name":"29"
    },
    {
      "no":29,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:50:68",
      "name":"30"
    },
    {
      "no":30,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:31:00",
      "name":"31"
    },
    {
      "no":31,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"02:01:33",
      "name":"32"
    },
    {
      "no":32,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:13:27",
      "name":"33"
    },
    {
      "no":33,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:18:14",
      "name":"34"
    },
    {
      "no":34,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:55:09",
      "name":"35"
    }
  ]
}
renderer.js:56 Array(35)
renderer.js:56 false
renderer.js:56 ready
renderer.js:56 Object
renderer.js:56 progress Idle
renderer.js:56 transfer-completed
renderer.js:56 Object
renderer.js:56 Processing track: 36
renderer.js:56 Directory createdC:\Users\Ender\AppData\Local\Temppmd-temp
renderer.js:56 C:\Users\Ender\Desktop\New folder\CD1-37.mp3
renderer.js:56 Starting conversion in <SP> mode
renderer.js:56 progress Converting to Wav
renderer.js:56 Starting WAV conversion process using ffmpeg: C:\Users\Ender\Desktop\New folder\CD1-37.mp3 --> C:\Users\Ender\AppData\Local\Temppmd-temp\ƒgƒ‰ƒbƒN 37 - No Artist.wav
renderer.js:56 Spawned Ffmpeg with command:  ffmpeg -i C:\Users\Ender\Desktop\New folder\CD1-37.mp3 -y -ar 44100 -acodec pcm_s16le C:\Users\Ender\AppData\Local\Temppmd-temp\ƒgƒ‰ƒbƒN 37 - No Artist.wav`

It just skips a track and then keeps going.  Usually will only skip one, but it will skip another later on.

Eventually it errored out completely and stopped transfering:

`Array(37)
renderer.js:56 false
renderer.js:56 ready
renderer.js:56 Object
renderer.js:56 progress Idle
renderer.js:56 audio file size : 12395698 bytes

renderer.js:56 supported audio file detected
data chunk position at 170
audio data size read from file :           12395520 bytes
audio data size calculated from file size: 12395520 bytes

renderer.js:56 netmd_acquire_dev: No error

renderer.js:56 netmd_secure_leave_session : Unknown Error

renderer.js:56 netmd_secure_set_track_protection : No error

renderer.js:56 netmd_secure_enter_session : No error

renderer.js:56 netmd_secure_send_key_data : No error

renderer.js:56 netmd_secure_session_key_exchange : No error

renderer.js:56 netmd_secure_setup_download : No error

renderer.js:56 generating packet 1 : 1048552 bytes

renderer.js:56 generating packet 2 : 1048576 bytes

renderer.js:56 generating packet 3 : 1048576 bytes

renderer.js:56 generating packet 4 : 1048576 bytes

renderer.js:56 generating packet 5 : 1048576 bytes

renderer.js:56 generating packet 6 : 1048576 bytes

renderer.js:56 generating packet 7 : 1048576 bytes

renderer.js:56 generating packet 8 : 1048576 bytes

renderer.js:56 generating packet 9 : 1048576 bytes

renderer.js:56 generating packet 10 : 1048576 bytes

renderer.js:56 generating packet 11 : 1048576 bytes
last packet: packet_data_length=861208 + frame_padding=1024 = chunksize=862232

renderer.js:56 generating packet 12 : 862232 bytes
netmd_prepare_packets : No error
total transfer size : 12396568 bytes, 6053 frames of 2048 bytes

renderer.js:56 1048576 of 12396568 bytes (8%) transferred (1048576 of 1048576 bytes in packet)

renderer.js:56 progress Transferring: 39
renderer.js:56 2097152 of 12396568 bytes (16%) transferred (1048576 of 1048576 bytes in packet)

renderer.js:56 progress Transferring: 39
renderer.js:56 3145728 of 12396568 bytes (25%) transferred (1048576 of 1048576 bytes in packet)

renderer.js:56 progress Transferring: 39
renderer.js:56 4194304 of 12396568 bytes (33%) transferred (1048576 of 1048576 bytes in packet)

renderer.js:56 progress Transferring: 39
renderer.js:56 5242880 of 12396568 bytes (42%) transferred (1048576 of 1048576 bytes in packet)

renderer.js:56 progress Transferring: 39
renderer.js:56 6291456 of 12396568 bytes (50%) transferred (1048576 of 1048576 bytes in packet)

renderer.js:56 progress Transferring: 39
renderer.js:56 7340032 of 12396568 bytes (59%) transferred (1048576 of 1048576 bytes in packet)

renderer.js:56 progress Transferring: 39
renderer.js:56 8388608 of 12396568 bytes (67%) transferred (1048576 of 1048576 bytes in packet)

renderer.js:56 progress Transferring: 39
renderer.js:56 9437184 of 12396568 bytes (76%) transferred (1048576 of 1048576 bytes in packet)

renderer.js:56 progress Transferring: 39
renderer.js:56 10485760 of 12396568 bytes (84%) transferred (1048576 of 1048576 bytes in packet)

renderer.js:56 progress Transferring: 39
renderer.js:56 11534336 of 12396568 bytes (93%) transferred (1048576 of 1048576 bytes in packet)

renderer.js:56 progress Transferring: 39
renderer.js:56 12396568 of 12396568 bytes (100%) transferred (862232 of 862232 bytes in packet)

renderer.js:56 progress Transferring: 39
renderer.js:56 netmd_transfer_song_packets : transfer took 18 seconds (672 kB/sec)

renderer.js:56 netmd_secure_send_track : No error

renderer.js:56 New Track: 37

renderer.js:56 netmd_secure_commit_track : No error

renderer.js:56 netmd_secure_session_key_forget : No error

renderer.js:56 netmd_secure_leave_session : No error

renderer.js:56 netmd_release_dev : Unknown Error

renderer.js:56 netmdcli send returned Success code 0
renderer.js:56 no-connection
renderer.js:56 {eventType: "no-connection", deviceName: ""}
renderer.js:56 Attempting to read from NetMD
renderer.js:56 progress Idle
renderer.js:56 transfer-completed
renderer.js:56 {eventType: "transfer-completed", isBusy: false}
renderer.js:56 Processing track: 39
renderer.js:7 TypeError: Cannot read property 'fileName' of undefined
    at a.<anonymous> (file:///C:/Users/Ender/AppData/Local/Programs/platinum-md/resources/app.asar/dist/electron/renderer.js:56:399234)
    at b (file:///C:/Users/Ender/AppData/Local/Programs/platinum-md/resources/app.asar/dist/electron/renderer.js:30:18000)
    at Generator._invoke (file:///C:/Users/Ender/AppData/Local/Programs/platinum-md/resources/app.asar/dist/electron/renderer.js:30:17753)
    at Generator.forEach.t.(anonymous function) [as next] (file:///C:/Users/Ender/AppData/Local/Programs/platinum-md/resources/app.asar/dist/electron/renderer.js:30:18180)
    at o (file:///C:/Users/Ender/AppData/Local/Programs/platinum-md/resources/app.asar/dist/electron/renderer.js:1:9014)
    at file:///C:/Users/Ender/AppData/Local/Programs/platinum-md/resources/app.asar/dist/electron/renderer.js:1:9111
    at <anonymous>
Yt @ renderer.js:7
Wt @ renderer.js:7
Ut @ renderer.js:7
(anonymous) @ renderer.js:7
renderer.js:56 {
  "device":"Sony LAM-10",
  "title":"<Untitled>",
  "recordedTime":"00:40:14.00",
  "totalTime":"01:20:59.11",
  "availableTime":"00:40:45.90",
  "tracks":[
    {
      "no":0,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:24:61",
      "name":"1"
    },
    {
      "no":1,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:48:29",
      "name":"2"
    },
    {
      "no":2,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:34:00",
      "name":"3"
    },
    {
      "no":3,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:50:50",
      "name":"4"
    },
    {
      "no":4,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:46:75",
      "name":"5"
    },
    {
      "no":5,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:47:11",
      "name":"6"
    },
    {
      "no":6,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:50:00",
      "name":"7"
    },
    {
      "no":7,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:29:24",
      "name":"8"
    },
    {
      "no":8,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:19:25",
      "name":"9"
    },
    {
      "no":9,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:34:03",
      "name":"10"
    },
    {
      "no":10,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:41:33",
      "name":"11"
    },
    {
      "no":11,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:51:63",
      "name":"12"
    },
    {
      "no":12,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:43:22",
      "name":"13"
    },
    {
      "no":13,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:12:14",
      "name":"14"
    },
    {
      "no":14,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:28:42",
      "name":"15"
    },
    {
      "no":15,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:20:67",
      "name":"16"
    },
    {
      "no":16,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:51:24",
      "name":"17"
    },
    {
      "no":17,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:37:17",
      "name":"18"
    },
    {
      "no":18,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:34:75",
      "name":"19"
    },
    {
      "no":19,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:43:42",
      "name":"20"
    },
    {
      "no":20,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:05:00",
      "name":"21"
    },
    {
      "no":21,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:12:85",
      "name":"22"
    },
    {
      "no":22,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:46:04",
      "name":"23"
    },
    {
      "no":23,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:45:65",
      "name":"24"
    },
    {
      "no":24,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:04:76",
      "name":"25"
    },
    {
      "no":25,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:41:38",
      "name":"26"
    },
    {
      "no":26,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:44:00",
      "name":"27"
    },
    {
      "no":27,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:14:21",
      "name":"28"
    },
    {
      "no":28,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:49:70",
      "name":"29"
    },
    {
      "no":29,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:50:68",
      "name":"30"
    },
    {
      "no":30,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:31:00",
      "name":"31"
    },
    {
      "no":31,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"02:01:33",
      "name":"32"
    },
    {
      "no":32,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:13:27",
      "name":"33"
    },
    {
      "no":33,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:18:14",
      "name":"34"
    },
    {
      "no":34,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:55:09",
      "name":"35"
    },
    {
      "no":35,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"00:46:31",
      "name":"37"
    },
    {
      "no":36,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:55:50",
      "name":"38"
    },
    {
      "no":37,
      "protect":"UnPROT",
      "bitrate":"SP",
      "time":"01:10:59",
      "name":"39"
    }
  ]
}
renderer.js:56 (38) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, __ob__: Tt]
renderer.js:56 false
renderer.js:56 ready
renderer.js:56 {eventType: "ready"}
renderer.js:56 progress Idle`

Neither of these two errors occur with SS or when transferring directly from CD -> MD

No clue if any of this helps, but I figure I'd point it out.
